services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7331:7331"
    environment:
      - UPLOAD_PATH=/app/uploads
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/db.sqlite
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "100M"
        max-file: "3"
